### ISSUE TITLE
Would you be interested if instead of a TextArea we used Monaco editor ?

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Fable.SimpleXml#4]
The benefit of Monaco editor, could be:

- basic intellisense
- Pressing `Tab`key support (no switching active element of the page)
- Show line number
- Coloration synthax support

I could send a PR later to add the support of Monaco as I am already using it in a really similar project of yours

**Comment by Zaid-Ajaj** [comment]
Yeah Monano would be nice to have but I just wanted a dead simple test page to see the results real quick :smile:

**Comment by MangelMaxime** [comment]
No problem, will add it later :)

For now, I am testing if your lib so I don't have to write an html parser myself ^^

**Comment by Zaid-Ajaj** [comment]
It should work fine if your html is well-formed xml, usually that is not the case :( you can try it anyway, let me know how it goes :smile: 

> Note that parsing comments doesn't work yet
