### ISSUE TITLE
Parsing fails if text contains '>'

### ISSUE THREAD

**Issue by davedawkins** [Zaid-Ajaj/Fable.SimpleXml#46]
```xml
<?xml version="1.0" encoding="utf-8"?>
<doc>
This should parse but fails >
</doc>
```

Online validators pass this example. I think I might be able to fix it, will submit a PR. I may try to fix the other issue about numeric tag names too.

**Comment by Zaid-Ajaj** [comment]
> I think I might be able to fix it, will submit a PR. I may try to fix the other issue about numeric tag names too.

That would be great :pray:

**Comment by davedawkins** [comment]
This is fixed, PR soon

**Comment by Zaid-Ajaj** [comment]
Fixed as of Fable.SimpleXml v3.4.0 🚀 thanks to @davedawkins
