### ISSUE TITLE
Parser fail if a tag is inlined inside a text string

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Fable.SimpleXml#5]
Considering the following code:

```html
<div class="container">
  <div class="notification">
    This container is <strong>centered</strong> on desktop.
  </div>
</div>
```

The parser is failing to parse it. I tried to run it against some validator and it seems to be a valid format.

**Comment by Zaid-Ajaj** [comment]
Correct, this is a bug, the reason is that there is either just text inside an element or child elements. The parser should be able to read the text as `TextNode`

**Comment by Zaid-Ajaj** [comment]
Oh man this was really mind boggling hahah but it is fixed now :smile: :smile: I added parsing mixed nodes which means this snippet:
```xml
This container is <strong>centered</strong> on desktop.
```
will be parsed as something like this (psuedo-code):
```
TextNode("This container is ")
Node("strong", "centered", Children())
TextNode("on desktop.")
```

**Comment by MangelMaxime** [comment]
@Zaid-Ajaj Thanks you, I think this should give enough information to the end user :) :clap:
